POST http://localhost:3000/api/users
Content-Type: application/json

{
  "id": "eko",
  "name": "Eko",
  "password": "rahasia"
}

###

POST http://localhost:3000/api/users/_login
Content-Type: application/json

{
  "id": "eko",
  "password": "rahasia"
}

###

GET http://localhost:3000/api/users/_current
Authorization: 550e8400-e29b-41d4-a716-446655440092